version: '3'
services:
    mysql:
        image: "mysql:5.7"
        ports:
            - "33061:3306"
        volumes:
            - ./docker_data/mysql/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

