version: '3'
services:
    mysql:
        image: "mysql:5.7"
        ports:
            - "33061:3306"
        volumes:
            - ./docker_data/mysql/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    rabbit:
        image: "rabbitmq:alpine"
        ports:
            - "56721:5672"
        volumes:
            - ./docker_data/rabbitmq/:/var/lib/rabbitmq
    mailserver:
        image: "mailhog/mailhog:latest"
        ports:
            - "8025:8025"
            - "1025:1025"
